// astro/src/components/Button.jsx
import React, { useEffect, useState } from 'react'

const Button = ({ children, ...props }) => {
  const [count, setCount] = useState(0)

  const handleClick = () => {
    setCount(prev => prev + 1)
  }

  useEffect(() => {
    console.log('mounted')
  },[])

  return (
    <button type={'button'} onClick={handleClick} {...props} >
      {children}
      <span>:{count}</span>
    </button>
  )
}

export default Button

// qwik/src/components/Button/index.tsx
import { component$, useStore, useClientEffect$, Slot } from "@builder.io/qwik";

const Button = component$(() => {
  const store = useStore({ count: 0 });

  useClientEffect$(() => {
    console.log("mounted");
  });

  return (
    <button type={"button"} onClick$={() => store.count++}>
      <Slot />
      <span>:{store.count}</span>
    </button>
  );
});

export default Button;
